### ISSUE TITLE
Warn of outdated content

### ISSUE THREAD

**Issue by CloudLing20** [Marikider/SCP1162#1]
Visual Studio issued a warning. I'm not sure whether this will affect the use, I just tell you that there is this problem.
Warning content :
“GameObject.active” Deprecated:“GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.” SCP1162 Plugin.cs 82

**Comment by Mar1ki** [comment]
I rewrote code like a year ago....

**Comment by CloudLing20** [comment]
> I rewrote code like a year ago....

Sorry, I forgot about this issue, so I haven't closed it yet.
